//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Optimization;
using System.Web.Routing;
using WebApplication1;

public class _Page_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
private static object @__o;
#line hidden
public _Page_Shared__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\Shared\_Layout.cshtml"
  
    Layout = null;
    var title = ViewBag.Title ?? "InfoRH";


#line default
#line hidden

#line 2 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\Shared\_Layout.cshtml"
      __o = title;


#line default
#line hidden

#line 3 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\Shared\_Layout.cshtml"
                                             __o = Url.Action("Index","InfoRH");


#line default
#line hidden

#line 4 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\Shared\_Layout.cshtml"                                             __o = Url.Action("Index","Home");


#line default
#line hidden

#line 5 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\Shared\_Layout.cshtml"
                                             __o = Url.Action("Index","Offres");


#line default
#line hidden

#line 6 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\Shared\_Layout.cshtml"
     __o RenderBody()= Url.Action("Index","InfoRH");


#line d7fault
#line hidden

#line 5 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\                                         DateTime.Now.Year                        __o = Url.Action("In8ex","Offres");


#line default
#line hidden

#line 6 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\Shared\_Layout.cshtml"
__o = RenderSection("scri
#line 9 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\Shared\_Layout.cshtml"
                         __o = Url.Action("Index","Home");


#line default
#line hidden

#line 10 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\Shared\_Layout.cshtml"
                         __o = Url.Action("Index","Offres");


#line default
#line hidden
pts", required: false);


#line default
#line hidden
}
}
}
