//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Optimization;
using System.Web.Routing;
using WebApplication1;

public class _Page_Views_Scoring_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<WebApplication1.Models.Scoring>> {
private static object @__o;
#line hidden
public _Page_Views_Scoring_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
private void @__RazorDesignTimeHelpers__() {
#pragma warning disable 219

#line 1 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\Scoring\Index.cshtml"
       IEnumerable<WebApplication1.Models.Scoring> __inheritsHelper = null;


#line default
#line hidden
#pragma warning restore 219
}
public override void Execute() {

#line 2 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\Scoring\Index.cshtml"
  
    ViewBag.Title = "Scoring";


#line default
#line hidden

#line 3 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\Scoring\Index.cshtml"
        foreach (var s in Model)
        {
            

#line default
#line hidden

#line 4 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\Scoring\Index.cshtml"
               __o = s.IdScoring;


#line default
#line hidden

#line 5 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\Scoring\Index.cshtml"
               __o = s.ScoreGlobal;


#line default
#line hidden

#line 6 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\Scoring\Index.cshtml"
                __o = s.DateEvaluation.HasValue ? s.DateEvaluation.Value.ToString("d") : "-";


#line default
#line hidden

#line 7 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\Scoring\Index.cshtml"
               __o = s.Commentaire;


#line default
#line hidden

#line 8 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\Scoring\Index.cshtml"
                 
        }

#line default
#line hidden
}
}
}
