//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Optimization;
using System.Web.Routing;
using WebApplication1;

public class _Page_Views_ProfilEmploye_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<WebApplication1.Models.ProfilEmploye>> {
private static object @__o;
#line hidden
public _Page_Views_ProfilEmploye_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
private void @__RazorDesignTimeHelpers__() {
#pragma warning disable 219

#line 1 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\ProfilEmploye\Index.cshtml"
       IEnumerable<WebApplication1.Models.ProfilEmploye> __inheritsHelper = null;


#line default
#line hidden
#pragma warning restore 219
}
public override void Execute() {

#line 2 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\ProfilEmploye\Index.cshtml"
  
    ViewBag.Title = "Profil Employés";


#line default
#line hidden

#line 3 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\ProfilEmploye\Index.cshtml"
        foreach (var e in Model)
        {
            

#line default
#line hidden

#line 4 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\ProfilEmploye\Index.cshtml"
lEmploye\Index.cshtmlm.Nom             __o = e.Nom;


#line default5
#line hidden

#line 5 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\ProfilEmploye\Index.cshtmlm.Prenom          __o = e.Prenom;


#line default6
#line hidden

#line 6 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\ProfilEmploye\Index.cshtmll.Email           __o = e.Email;


#line default7
#line hidden

#line 7 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\ProfilEmploye\Index.cshtmle.Telephone       __o = e.Telephone;


#line default8
#line hidden

#line 8 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\ProfilEmploye\Index.cshtml"
                __o = e.DateEmbauche.ToString("d");


#line default9
#line hidden

#line 9 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\ProfilEmploye\Index.cshtml"
                __o = e.Postes?.Intitule ?? "(N/A)";


#line default10#line hidden

#line 10 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\ProfilEmploye\Index.cshtml"
                __o = e.Diplomes?.NomDiplome ?? "(N/A)";


#line default11#line hidden

#line 11 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\ProfilEmploye\Index.cshtml"
                __o = e.StatutActif ? "Actif" : "Inactif";


#line default12#line hidden

#line 12 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\ProfilEmploye\Index.cshtml"
                                                                              __o = Url.Action("Details","ProfilEmploye", new { id = e
#line default
#line hidden

#line 13 "C:\Users\prote\AppData\Local\Temp\FF3F08549E9086C7B5AB5DCFFF406C04A963\7\WebApplication1\WebApplication1\Views\ProfilEmploye\Index.cshtml"
                 
        }
           
        }

#line default
#line hidden
}
}
}
