//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;

    public partial class HistoriqueEmploye
    {
        public int IdHistoriqueEmploye { get; set; }
        public System.DateTime DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public string SuiviHierarchique { get; set; }
        public double Salaire { get; set; }
        public string EvaluationPerformance { get; set; }
        public string PosteOccupe { get; set; }
        public string Departement { get; set; }
        public string TypeContrat { get; set; }
        public string MotifFinContrat { get; set; }
        public string CommentairesRH { get; set; }
        public int IdEmploye { get; set; }

        public virtual ProfilEmploye ProfilEmploye { get; set; }
    }
}