//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities4 : DbContext
    {
        public Database1Entities4()
            : base("name=Database1Entities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProfilEmploye> ProfilEmploye { get; set; }
        public virtual DbSet<ProfilExterne> ProfilExterne { get; set; }
        public virtual DbSet<CriteresEligibilite> CriteresEligibilite { get; set; }
        public virtual DbSet<Diplomes> Diplomes { get; set; }
        public virtual DbSet<HistoriqueEmploye> HistoriqueEmploye { get; set; }
        public virtual DbSet<OffresEmploi> OffresEmploi { get; set; }
        public virtual DbSet<Postes> Postes { get; set; }
        public virtual DbSet<ProfilScoring> ProfilScoring { get; set; }
        public virtual DbSet<Scoring> Scoring { get; set; }
    }
}
