//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OffresEmploi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OffresEmploi()
        {
            this.CriteresEligibilite = new HashSet<CriteresEligibilite>();
            this.ProfilEmploye = new HashSet<ProfilEmploye>();
            this.ProfilExterne = new HashSet<ProfilExterne>();
        }
    
        public int IdOffreEmploi { get; set; }
        public string IntitulePoste { get; set; }
        public string Localisation { get; set; }
        public string NiveauPoste { get; set; }
        public System.DateTime DatePublication { get; set; }
        public string Disponibilite { get; set; }
        public bool TeletravailPossible { get; set; }
        public string TypeContrat { get; set; }
        public double SalairePropose { get; set; }
        public string Description { get; set; }
        public System.DateTime DateLimiteCandidature { get; set; }
        public int NbPostesOuverts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CriteresEligibilite> CriteresEligibilite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfilEmploye> ProfilEmploye { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfilExterne> ProfilExterne { get; set; }
    }
}
