//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postes()
        {
            this.ProfilEmploye = new HashSet<ProfilEmploye>();
        }
    
        public int IdPoste { get; set; }
        public string Intitule { get; set; }
        public string NiveauDiplomeRequis { get; set; }
        public string NiveauHierarchique { get; set; }
        public string Description { get; set; }
        public bool MobiliteRequise { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfilEmploye> ProfilEmploye { get; set; }
    }
}
