//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfilExterne
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfilExterne()
        {
            this.ProfilScoring = new HashSet<ProfilScoring>();
        }
    
        public int IdProfilExterne { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public System.DateTime DateNaissance { get; set; }
        public string Adresse { get; set; }
        public string Sexe { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public System.DateTime DateCandidature { get; set; }
        public int IdDiplome { get; set; }
        public int IdOffreEmploi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfilScoring> ProfilScoring { get; set; }
        public virtual Diplomes Diplomes { get; set; }
        public virtual OffresEmploi OffresEmploi { get; set; }
    }
}
