//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfilEmploye
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfilEmploye()
        {
            this.HistoriqueEmploye = new HashSet<HistoriqueEmploye>();
        }
    
        public int IdProfilEmploye { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public System.DateTime DateNaissance { get; set; }
        public string Adresse { get; set; }
        public string Sexe { get; set; }
        public int NbCongesRestants { get; set; }
        public string TypeContrat { get; set; }
        public string LocalisationPoste { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public System.DateTime DateEmbauche { get; set; }
        public Nullable<System.DateTime> DateFinContrat { get; set; }
        public bool StatutActif { get; set; }
        public int NbHeuresHebdo { get; set; }
        public int IdDiplome { get; set; }
        public int IdPosteActuel { get; set; }
        public Nullable<int> IdOffreSouhaitee { get; set; }
    
        public virtual Diplomes Diplomes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoriqueEmploye> HistoriqueEmploye { get; set; }
        public virtual OffresEmploi OffresEmploi { get; set; }
        public virtual Postes Postes { get; set; }
    }
}
