//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scoring
    {
        public int IdScoring { get; set; }
        public Nullable<double> ScoreGlobal { get; set; }
        public Nullable<System.DateTime> DateEvaluation { get; set; }
        public string Commentaire { get; set; }
    }
}
